"""Add mortgage and overdraft account types

Revision ID: 14caf3f330ee
Revises: 5a7a71a7ab0b
Create Date: 2026-03-23 22:56:35.890607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "14caf3f330ee"
down_revision: Union[str, Sequence[str], None] = "5a7a71a7ab0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
