"""Initial migration

Revision ID: 3bb02c689d40
Revises: 3cab4bf30b5a
Create Date: 2026-01-22 18:37:54.507959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb02c689d40'
down_revision = '3cab4bf30b5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
