"""Add auto-generation fields to income_sources

Revision ID: 412ce027e335
Revises: 60718be7d371
Create Date: 2026-03-26 11:10:42.014333

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "412ce027e335"
down_revision: Union[str, Sequence[str], None] = "60718be7d371"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "income_history",
        sa.Column("skip_auto_generation", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "income_sources",
        sa.Column("auto_generate_entries", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "income_sources",
        sa.Column("generate_if_manual_exists", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "income_sources",
        sa.Column("generate_on_weekends", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "income_sources", sa.Column("next_generation_date", sa.Date(), nullable=True)
    )
    op.add_column(
        "income_sources", sa.Column("last_generated_date", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("income_sources", "last_generated_date")
    op.drop_column("income_sources", "next_generation_date")
    op.drop_column("income_sources", "generate_on_weekends")
    op.drop_column("income_sources", "generate_if_manual_exists")
    op.drop_column("income_sources", "auto_generate_entries")
    op.drop_column("income_history", "skip_auto_generation")
    # ### end Alembic commands ###
