"""Add balance constraints

Revision ID: 5a7a71a7ab0b
Revises: e63de39e4ccc
Create Date: 2026-03-19 23:07:35.144498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5a7a71a7ab0b"
down_revision: Union[str, Sequence[str], None] = "e63de39e4ccc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
