"""Add refresh token fields to users

Revision ID: 60718be7d371
Revises: 7a76e35711f6
Create Date: 2026-03-26 08:36:00.377647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "60718be7d371"
down_revision: Union[str, Sequence[str], None] = "7a76e35711f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("refresh_token", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("refresh_token_expires", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "refresh_token_expires")
    op.drop_column("users", "refresh_token")
    # ### end Alembic commands ###
