"""Add status and currency fields to accounts

Revision ID: 7a76e35711f6
Revises: 14caf3f330ee
Create Date: 2026-03-23 23:55:22.674059

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7a76e35711f6"
down_revision: Union[str, Sequence[str], None] = "14caf3f330ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("status", sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "status")
    # ### end Alembic commands ###
